name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup AMBuild
      run: pip install --user --upgrade git+https://github.com/alliedmodders/ambuild

    - name: Configure build
      run: |
        mkdir build && cd build
        python ../configure.py -s cs2 --no-mysql

    - name: Compile
      run: |
        cd build
        ambuild

    - name: Package
      run: |
        cd build/package
        ls

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LuaUnlocker-windows
        path: build/package/*

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gcc-multilib g++-multilib

    - name: Setup AMBuild
      run: pip3 install --user --upgrade git+https://github.com/alliedmodders/ambuild

    - name: Configure build
      run: |
        mkdir build && cd build
        python3 ../configure.py -s cs2 --no-mysql

    - name: Compile
      run: |
        cd build
        ambuild

    - name: Package
      run: |
        cd build/package
        ls

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LuaUnlocker-linux
        path: build/package/*
